web:
  build: .
  ports:
    - "80:80"
  links:
    - db
  volumes:
    - .:/code
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
     - 8080:80
    links:
      - db
db:
  image: "mysql:5"
  container_name: database.dev
  command: mysqld --user=root --verbose
  volumes:
    - ./mysql:/etc/mysql/conf.d
    - ./noticeboard.sql:/tmp/noticeboard.sql
    - ./import.sh:/tmp/import.sh
  environment:
    MYSQL_ROOT_PASSWORD: phpapptest
    MYSQL_DATABASE: noticeboard
